steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/mysleepr-413821/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        'push', 'southamerica-east1-docker.pkg.dev/mysleepr-413821/reservations/production',
      ]
  # auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/mysleepr-413821/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        'push', 'southamerica-east1-docker.pkg.dev/mysleepr-413821/auth/production',
      ]
  # notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/mysleepr-413821/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        'push', 'southamerica-east1-docker.pkg.dev/mysleepr-413821/notifications/production',
      ]
  # payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/mysleepr-413821/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        'push', 'southamerica-east1-docker.pkg.dev/mysleepr-413821/payments/production',
      ]