version: '1'
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
